server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: subscriptionRoute
          uri: http://localhost:8087
          predicates:
            - Path=//subscription/**
        - id: courseRoute
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/course/**
