server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: subscriptionRoute
          uri: lb://SUBSCRIPTION-SERVICE
          predicates:
            - Path=//subscription/**
        #  filters:
        #    - name: SubscriptionFilter
        - id: courseRoute
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/course/**
        - id: studentRoute
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/student/**
          filters:
            - AddRequestHeader=course-request-header, custom-course-request-header
            - AddResponseHeader=course-response-header, custom-course-response-header
